services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true
    bind:
      '$projectDir': '%kernel.project_dir%'

  WEM\CommandBundle\:
    resource: '../src'
    exclude: '../src/{ContaoManager,DependencyInjection}'

  WEM\CommandBundle\Controller\BackendCommandController:
    arguments:
      $kernel: '@kernel'
    public: false